In [7]:
import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib import pyplot as plt
plt.rcParams.update({'font.size': 22})
import numpy as np
import itertools
import qml.representations
import qml.kernels.distance
import sys
sys.path.insert(0, '/home/misa/APDFT/prototyping/atomic_energies/')

In [2]:
c_atom = np.array([0.0, 0.0, 0.0])
n_atom = np.array([1.5, 1.5, 0.0])
b_atom = np.array([-1.5, 1.5, 0.0])
delta = np.array([-0.1, 0.0, 0.0])
atoms = np.array([c_atom,b_atom,n_atom])
conf0 = qml.representations.generate_atomic_coulomb_matrix(np.array([6,5,7]), atoms, size=3, sorting='distance')

atoms_d1p = atoms.copy()
atoms_d1p[1:3] = atoms_d1p[1:3] + delta
conf_d1p = qml.representations.generate_atomic_coulomb_matrix(np.array([6,5,7]), atoms_d1p, size=3, sorting='distance')

atoms_d1m = atoms.copy()
atoms_d1m[1:3] = atoms_d1m[1:3] - delta
conf_d1m = qml.representations.generate_atomic_coulomb_matrix(np.array([6,5,7]), atoms_d1m, size=3, sorting='distance')

In [12]:
conf0[0]

array([36.8581052 , 14.14213562, 23.79567423, 19.79898987, 11.66666667,
       53.3587074 ])

In [13]:
conf_d1m[0]

array([36.8581052 , 14.62110536, 23.79567423, 19.15035161, 11.66666667,
       53.3587074 ])

In [14]:
atoms_d1m

array([[ 0. ,  0. ,  0. ],
       [-1.4,  1.5,  0. ],
       [ 1.6,  1.5,  0. ]])

In [8]:
qml.kernels.distance.l2_distance(conf0, conf0)

array([[ 0.        , 21.76059666, 37.69791152],
       [21.76059666,  0.        , 42.56695737],
       [37.69791152, 42.56695737,  0.        ]])

In [9]:
qml.kernels.distance.l2_distance(conf_d1p, conf0)

array([[42.72515007, 37.77683813, 23.56196323],
       [22.02485542,  0.81505001, 42.72515007],
       [37.77683813, 42.72515007,  0.81505001]])

In [10]:
qml.kernels.distance.l2_distance(conf_d1m, conf0)

array([[ 0.80631483, 21.53192603, 37.49418462],
       [21.53192603,  0.80631483, 42.42450442],
       [37.64061001, 42.42450442,  0.80631483]])

In [11]:
conf_d1m

array([[36.8581052 , 14.62110536, 23.79567423, 19.15035161, 11.66666667,
        53.3587074 ],
       [23.79567423, 14.62110536, 36.8581052 , 11.66666667, 19.15035161,
        53.3587074 ],
       [53.3587074 , 19.15035161, 36.8581052 , 11.66666667, 14.62110536,
        23.79567423]])

In [18]:
c_atom = np.array([0.0, 0.0, 0.0])
n_atom = np.array([1.5, 1.5, 0.0])
b_atom = np.array([-1.5, 1.5, 0.0])
delta = np.array([-0.1, 0.0, 0.0])
atoms = np.array([c_atom,b_atom,n_atom])

conf0 = qml.representations.generate_atomic_coulomb_matrix(np.array([6,5,7]), atoms, size=3, sorting='row-norm')

atoms_d1p = atoms.copy()
atoms_d1p[1:3] = atoms_d1p[1:3] + delta
conf_d1p = qml.representations.generate_atomic_coulomb_matrix(np.array([6,5,7]), atoms_d1p, size=3, sorting='row-norm')

atoms_d1m = atoms.copy()
atoms_d1m[1:3] = atoms_d1m[1:3] - delta
conf_d1m = qml.representations.generate_atomic_coulomb_matrix(np.array([6,5,7]), atoms_d1m, size=3, sorting='row-norm')

In [19]:
conf0

array([[36.8581052 , 19.79898987, 53.3587074 , 14.14213562, 11.66666667,
        23.79567423],
       [23.79567423, 11.66666667, 53.3587074 , 14.14213562, 19.79898987,
        36.8581052 ],
       [53.3587074 , 19.79898987, 36.8581052 , 11.66666667, 14.14213562,
        23.79567423]])

In [20]:
qml.kernels.distance.l2_distance(conf0, conf0)

array([[ 0.        , 21.76059666, 23.59651752],
       [21.76059666,  0.        , 37.69791152],
       [23.59651752, 37.69791152,  0.        ]])

In [21]:
qml.kernels.distance.l2_distance(conf_d1p, conf0)

array([[ 0.81505001, 22.02485542, 23.56196323],
       [22.02485542,  0.81505001, 37.77683813],
       [23.56196323, 37.9202454 ,  0.81505001]])

In [22]:
qml.kernels.distance.l2_distance(conf_d1m, conf0)

array([[ 0.80631483, 21.53192603, 23.66045503],
       [21.53192603,  0.80631483, 37.64061001],
       [23.66045503, 37.49418462,  0.80631483]])

In [92]:
# Coloumb Matrix carbon

# carbon row
cc = 0.5*6**2.4
cb = 5*6/(np.linalg.norm(c_atom-b_atom))
cn = 7*6/(np.linalg.norm(c_atom-b_atom))
norm_c= cc**2+cb**2+cn**2

# bor row
bb = 0.5*5**2.4
bc = 5*6/(np.linalg.norm(c_atom-b_atom))
bn = 7*5/(np.linalg.norm(n_atom-b_atom))
norm_b= bb**2+bc**2+bn**2

# nitrogen row
# bor row
nn = 0.5*7**2.4
nc = 7*6/(np.linalg.norm(c_atom-n_atom))
nb = 7*5/(np.linalg.norm(n_atom-b_atom))
norm_n= nn**2+nc**2+nb**2

In [93]:
print(cc, cb, cn, norm_c)
print(bb, bc, bn, norm_b)
print(nn, nc, nb, norm_n)

36.85810519942594 14.142135623730951 19.79898987322333 1950.5199188919496
23.79567423394848 14.142135623730951 11.666666666666666 902.3452233593106
53.3587073998281 19.79898987322333 11.666666666666666 3375.262766491581


In [94]:
conf0

array([[36.8581052 , 14.14213562, 23.79567423, 19.79898987, 11.66666667,
        53.3587074 ],
       [23.79567423, 14.14213562, 36.8581052 , 11.66666667, 19.79898987,
        53.3587074 ],
       [53.3587074 , 19.79898987, 36.8581052 , 11.66666667, 14.14213562,
        23.79567423]])